# DevOps Configuration File

[exclude]
buggy_cpp_macros = ["MSTD_WARN_BUGGY_HEADER", "MSTD_WARN_BUGGY_LIBRARY"]

[logging]
#global_level = "INFO"
#utils_level = "INFO"
#config_level = "INFO"
#cpp_level = "INFO"

[git]
#tag_prefix = ""
#empty_tag_list_allowed = true

[cpp]
#style_checks = true
#license_header_check = true
#check_only_staged_files = false
license_header = "config/licenseHeader.txt"
header_guards_according_to_filepath = true

[file]
#encoding = "utf-8"
