name: BUILD

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        build: [Release, Debug]
        gcc: [13, 14]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: install gcc${{ matrix.gcc}}
        run: |
          sudo apt update
          sudo apt install gcc-${{ matrix.gcc}} g++-${{ matrix.gcc}}
        shell: bash

      - name: Build and Test Project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build }} ..
          make -j2
          make test
        env:
          CC: gcc-13
          CXX: g++-13

